### ISSUE TITLE
Rooms not clickable in the viewer

### ISSUE THREAD

**Issue by lanlife** [apprentice3d/ForgeViewerExtensions#9]
Good day,
Well done and thank you for the vital job done.
I tried to re-implement the transformation sample with another model. I noticed the model could not select a room despite following the instruction here https://forge.autodesk.com/en/docs/model-derivative/v2/tutorials/prep-roominfo4viewer/. I used a Revit model 2022. Is the sample model from Revit?

**Comment by TulasigeriB** [comment]
this.viewer.disableSelection(true); 
comment this line u will able to select
